<?xml version="1.0"?>

<!DOCTYPE database [
  <!ELEMENT client (first,last,credit)>
  <!ATTLIST client id ID #REQUIRED>
  <!ATTLIST client related IDREFS #IMPLIED>

  <!ELEMENT first (#PCDATA)>
  <!ELEMENT last (#PCDATA)>

  <!ELEMENT credit EMPTY>
  <!ATTLIST credit limit CDATA #IMPLIED>
  <!ATTLIST credit currency CDATA #IMPLIED>
]>

<database>
  <!--
      Some info here
  -->
  <clients>
    <client id="id1" related="id2 id3 id4">
      <first> John </first>
      <last> Doe </last>
      <credit limit="10000" currency="USD"/>
    </client>

    <client id="id2">
      <first>Mary</first>
      <last>Doe</last>
      <credit limit="10000" currency="ILS"/>
    </client>
    <client id="id3">
      <first> Bob </first>
      <last> Doe </last>
      <credit limit="2000" currency="GBP"/>
    </client>
    <client id="id4" related = "id8">
      <first> Joe </first>
      <last> Public </last>
      <credit limit="5100" currency="GBP"/>
    </client>
    <client id="id5" related = "id3 id4">
      <first>Sally</first>
      <last>Public</last>
      <credit limit="5500" currency="GBP"/>
    </client>
    <client id="id6" related="id7 id8">
      <first> James </first>
      <last> Smith </last>
      <credit limit="1500" currency="USD"/>
    </client>
    <client id="id7">
      <first>Jack</first>
      <last> Smith </last>
      <credit limit="4500" currency="USD"/>
    </client>
    <client id="id8">
      <first> Ann </first>
      <last> Smith </last>
      <credit limit="2500" currency="USD"/>
    </client>

  </clients>

  <!--
      Some other info here
  -->
</database>
